name: Test
on: pull_request

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/cache@v2
        with:
          path: tests/chains/ethereum/contract/node_modules
          key: ${{ runner.os }}-ethereum-contract-${{ hashFiles('tests/chains/ethereum/contract/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ethereum-contract-
      - name: npm install
        working-directory: ./tests/chains/ethereum/contract
        run: npm install
      - name: Run geth node
        working-directory: ./tests/chains/ethereum
        run: |
          make docker-image
          make docker-run
      - name: Run Unit test
        run: go test -v --count=1 ./...
